<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://DefaultNamespace" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://DefaultNamespace" xmlns:intf="http://DefaultNamespace" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="TirarDado">

   </wsdl:portType>

   <wsdl:binding name="TirarDadoSoapBinding" type="impl:TirarDado">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="TirarDadoService">

      <wsdl:port binding="impl:TirarDadoSoapBinding" name="TirarDado">

         <wsdlsoap:address location="http://localhost:8080/ServicioWebDinamic/services/TirarDado"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
